#!/usr/bin/env python3
"""Build the file:// fallback bundle from assets/content/*.md."""

import json
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTENT_DIR = ROOT / "assets" / "content"
OUTPUT = ROOT / "assets" / "js" / "content.js"


def main() -> None:
    content = {
        path.stem: path.read_text(encoding="utf-8")
        for path in sorted(CONTENT_DIR.glob("*.md"))
    }
    payload = json.dumps(content, ensure_ascii=False, indent=2)
    OUTPUT.write_text(
        "// Generated by scripts/build_content.py; edit assets/content/*.md instead.\n"
        f"window.MARKDOWN_CONTENT = Object.freeze({payload});\n"
        f"window.CONTENT_LAST_UPDATED = \"{datetime.now().astimezone().date().isoformat()}\";\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
